package com.dongkap.panic.utils;

public final class ParameterEmergency {

	public static final String CATEGORY_EMERGENCY_FIRE = "CATEGORY_EMERGENCY.FIRE";
	public static final String CATEGORY_EMERGENCY_ABDUCTION = "CATEGORY_EMERGENCY.ABDUCTION";
	public static final String CATEGORY_EMERGENCY_THEFT = "CATEGORY_EMERGENCY.THEFT";
	public static final String CATEGORY_EMERGENCY_HER = "CATEGORY_EMERGENCY.HER";
	public static final String CATEGORY_EMERGENCY_UNREST = "CATEGORY_EMERGENCY.UNREST";
	public static final String CATEGORY_EMERGENCY_HARASSMENT = "CATEGORY_EMERGENCY.HARASSMENT";
	public static final String CATEGORY_EMERGENCY_THREAT = "CATEGORY_EMERGENCY.THREAT";
	public static final String CATEGORY_EMERGENCY_BULLYING = "CATEGORY_EMERGENCY.BULLYING";
	public static final String CATEGORY_EMERGENCY_OTHERS = "CATEGORY_EMERGENCY.OTHERS";
	public static final String CATEGORY_EMERGENCY_UNDEFINED = "CATEGORY_EMERGENCY.UNDEFINED";

}
