dongkap:
  signature:
    private-key: ${DONGKAP_SIGNATURE_PRIVATE_KEY:UHU3NG42QjNuNHI=}
    public-key: ${DONGKAP_SIGNATURE_PUBLIC_KEY:dc20c81f-1441-4f83-af98-454053772409}
    aes:
      secret-key: ${DONGKAP_AES_SECRET_KEY:UHVsYW5nQjNuNHI=}
    param-key: X-DONGKAP-Key
    param-timestamp: X-DONGKAP-Timestamp
    param-signature: X-DONGKAP-Signature
  locale: en-US
  client-id:
    web: do-core
  app-code:
    default: DONGKAP
  vapid:
    private-key: ${VAPID_PRIVATE_KEY:ZXPWGd9PkbSlyqvIxIzb1GN-la6fLm8TVEJsQxAR7IY}
    public-key: ${VAPID_PUBLIC_KEY:BB3fvY674t6pB9TjZONmYxxlebCmSskbf8lvRLTMYHE-zZ7FONNXOCPv4ndOa1FDov10k26UXZl6rQ7nT9sxWwc}
  recaptcha:
    site-key: ${RECAPTCHA_SITE_KEY:null}
    secret-key: ${RECAPTCHA_SECRET_KEY:null}
  notif:
    icon: ${ICON_NOTIFICATION:/assets/icons/icon-72x72.png}
    tag: panic
    default:
      is-admin: true
  file:
    path:
      tmp: ${PATH_TMP:./tmp/temps/}
      image:
        profile: ${PATH_IMAGE_PROFILE:./tmp/image/profile/}
      evidence: ${PATH_EVIDENCE:./tmp/evidence/}
  web:
    url:
      forgot-password: http://localhost:4200/auth/forgot-password
      activate-account: http://localhost:4200/auth/activate
  login:
    single-session: ${SINGLE_SESSION:false}

spring:
  mail:
    username: ridla.fadilah@gmail.com
mail:
  personal: panic
  
websocket:
  root:
    endpoint: /api/notification/ws
# Allow all hosts to bypass 'Access-Control-Allow-Origin' header. Not recommended to use in production.
  granted:
    hosts: '*'
  
security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: CfZKBe7IZHxBCgH9Dz49
      prefer-token-info: true

ribbon:
  eureka:
    enabled: false
feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        errorDecoder: com.dongkap.feign.decoder.FeignErrorDecoder
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        enabled: true
        forceOpen: false
        forceClosed: false
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      requestCache:
        enabled: true
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 15000
            interruptOnTimeout: true
            interruptOnFutureCancel: false
          semaphore:
            maxConcurrentRequests: 10
      fallback:
        enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 10

dongkap-master:
  ribbon:
    listOfServers: dongkap-master:8085
